### ISSUE TITLE
Setting up public server non functional

### ISSUE THREAD

**Issue by Qiangong2** [yuwui/Uchu#11]
Talked about this in the discord.

Right now, Uchu cannot be used as a public server due to certificate issues. Server is able to run and client can connext, but it errors out due to not being able to handle a cert

**Comment by Wincent01** [comment]
Latest commit message:
"
Transport Level Security (TLS) compatibility:

* Use a ".pfx" certificate. Place in <Certificate></Certificate> in the config file.
* TcpUdp requires a hostname to be provided, a dns. Place in <Hostname></Hostname>
* NOTE: this will slow down your connection, significantly.
"
