### ISSUE TITLE
Rocket crates only drop 3 out of 4 sets

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#150]
Accept Sky Lane's mission for collecting parts and try to collect all 4 colored rocket sets. You'll get different parts and duplicates as normal, but parts for one of the sets will never drop. Once you finish the 3 other sets (and the achievement to prove it), parts stop dropping entirely. The set in specific varies. I don't know what update caused this, but it's recent.

**Comment by TheNexusAvenger** [comment]
From my testing from last week, the classic rocket (white rocket) specifically is unobtainable. I never got any of the components as drops while I got the colored ones normally until all 3 colored rocket parts were obtained.

**Comment by MustacheMan2** [comment]
Still an issue, just not as often.

**Comment by TheNexusAvenger** [comment]
On the latest `dev` branch, I was able to get 11 of the 12 parts. Will be looking into why the parts stop spawning at 11/12 instead of 12/12.

**Comment by TheNexusAvenger** [comment]
After looking at the crate objects, I noticed that the rocket piece I didn't get (the yellow engine) is missing from the loot table.
![image](https://user-images.githubusercontent.com/13441476/107291699-8fe72300-6a36-11eb-972a-b67f28b2e701.png)

For reference:
- The Nose crate: https://lu-explorer.web.app/objects/4803/7
- The Cockpit crate: https://lu-explorer.web.app/objects/4805/7
- The Engine crate with the missing yellow engine: https://lu-explorer.web.app/objects/4804/7

**Comment by Xiphoseer** [comment]
There's also this one, which has the yellow but not the white engine: https://lu-explorer.web.app/objects/6377/7 and is attached to objects 3717614 - 3717617.

**Comment by TheNexusAvenger** [comment]
Can confirm that there are crates that do drop the yellow engine, although I find it strange that this is intended since the objects look the same.
![image](https://user-images.githubusercontent.com/13441476/107437299-c5564400-6afc-11eb-9213-d65b7d52669e.png)

**Comment by TheNexusAvenger** [comment]
Closing since this is resolved and the different crates appear to be intended.
