### ISSUE TITLE
Respawn Point Doesn't Change

### ISSUE THREAD

**Issue by TheNexusAvenger** [yuwui/Uchu#163]
When loading into worlds or getting smashed, the respawn point is always set to a specific location depending on the map. Most maps have multiple places where users can arrive from, but the initial location is always used. Additionally, if a player is smashed, or just leaves and rejoins, they are respawned the beginning of the map instead of a respawn point.

**Comment by Jettford** [comment]
There is a GM for this

**Comment by Jettford** [comment]
0x510 or PlayerReachedRespawnCheckpoint should be the one

**Comment by TheNexusAvenger** [comment]
There may be something more that is required. For some reason, I am not seeing the client sending this game message after completing a circuit of ~4 respawn checkpoints in Avant Gardens.

**Comment by Jettford** [comment]
That isn't how you should be checking if the client is sending game messages open up the packet captures it is definitely in there

**Comment by Jettford** [comment]
Oh didn't mean to close meant to comment

**Comment by Jettford** [comment]
![image](https://user-images.githubusercontent.com/55758076/104514089-9a093380-55e8-11eb-8a2b-4d53d96ff657.png)

Captures of it can be found in CheekyMonkey\Avant Gardens\Avant Gardens Survival with Golden Hammer(HappyHeavyStorm, IronFlashyHair, JetTwistTurkey)(made it to 638)

world2_traffic.zip

**Comment by enteryournamehere** [comment]
Implemented this in #239
