### ISSUE TITLE
Quick Builds with Preconditions Aren't Loaded Correctly

### ISSUE THREAD

**Issue by TheNexusAvenger** [yuwui/Uchu#166]
If a quick build requires a condition to be done (`CheckPrecondition` in the object's settings is populated), it is not set up properly on the client. The built item is not visible but acts as if it is done, while the quick build doesn't appear and displays THIS_QUICKBUILD_IS_NOT_READY_TO_BE_USED. Cases where this happens include:
- The rebuildable wall at Avant Gardens
- The vertical fan bouncer at the monument at Avant Gardens
- The finish line at the end of the road at Avant Gardens
- The Maelstrom Brick converter at Nimbus Station
- A build near the Assembly Brick Annex at Nimbus Station
- A build up the hill right after the launch area at Gnarled Forest
- The pirate Maelstrom walls at Gnarled Forest

**Comment by Jettford** [comment]
This applies for somethings but most of these are just invalid LWOOBJID assignments
