### ISSUE TITLE
Return To The Venture Explorer Corrupted Mechs Aren't Enemies

### ISSUE THREAD

**Issue by TheNexusAvenger** [yuwui/Uchu#168]
In Return To The Venture Explorer, Corrupted Mechs aren't loaded as being hostile. They do not attack players and can't be attacked by players.
![image](https://user-images.githubusercontent.com/13441476/104520034-733b0500-55c8-11eb-9a68-230629a0c196.png)

**Comment by Jettford** [comment]
This is a faction ID issue in the CDClient
