### ISSUE TITLE
Improve Uchu server documentation

### ISSUE THREAD

**Issue by zbdekrak** [yuwui/Uchu#180]
The Readme detailing how to install and configure Uchu is rather lackluster when it comes to detailing how to actually run the server. Details are also sparse on what world port binding is and why it's important. I recommend adding additional information on world, network and API ports, and a description of what the Uchu.Master console is and how to get to that point from editing the config.

**Comment by Jettford** [comment]
Uchu is complex software designed to be deployed to a server by a sys admin, it is not to host locally, if you can't work out what stuff does then you shouldn't really be setting up. It is a development server, us providing what is currently in the README is more than enough

**Comment by Wincent01** [comment]
Reopening issue. It it OK to suggest changes and Issues are the proper way to go about it. @Jettford, label it instead of closing similar issues in the future.

**Comment by elenawinters** [comment]
I'm going to self-assign this.

We get a lot of questions about setup in our Discord, and personally I'd like to reduce the amount of questions we get.

I'll go through the Readme over the next few weeks and improve on it.

I will agree with Jett though, that this is indeed a development server. We are usually quite generous in regards to support for our project though. Wincent is also right that issues are the proper way to go about suggestions or indeed actual issues.

Thanks for bringing this up!

**Comment by TheNexusAvenger** [comment]
Pull request #296 has been merged with some other changes that should make the setup from the code easier to understand. Pull request #298 will (hopefully) make releases viable instead of having everyone download, compile, and run Uchu.

I am closing this Issue for now. Please re-open or reply if there isn't something you aren't satisfied with.
