### ISSUE TITLE
Missions Don't Consume Items

### ISSUE THREAD

**Issue by TheNexusAvenger** [yuwui/Uchu#196]
There are a lot of missions that should consume items when completed, but currently don't. Some examples include:
- ["Secrets of the Maelstrom" (477)](https://lu-explorer.web.app/missions/477)
- ["Laser Rampage" (1854)](https://lu-explorer.web.app/missions/1854), *currently handled by a native script*
- ["Know Thy Enemy" (324)](https://lu-explorer.web.app/missions/324)
- ["Spare Cannonballs" (1158)](https://lu-explorer.web.app/missions/1158)
- ["Notion for a Potion" (865)](https://lu-explorer.web.app/missions/865)
- ["Of Vital Importance" (866)](https://lu-explorer.web.app/missions/866)
- ["Aid Me!" (867)](https://lu-explorer.web.app/missions/867)
- ["Peppy's Ugly Mug" (943)](https://lu-explorer.web.app/missions/943)
- ["Breadwinner" (1455)](https://lu-explorer.web.app/missions/1455)
- ["Ooh Ooh Eee Eee!" (228)](https://lu-explorer.web.app/missions/228)
- ["Collect Cannonballs" (230)](https://lu-explorer.web.app/missions/230)
- ["Name Dropper" (772)](https://lu-explorer.web.app/missions/772)
- ["Bell Buster" (509)](https://lu-explorer.web.app/missions/509)
- ["Power Pack" (739)](https://lu-explorer.web.app/missions/739)
- ["Sixteen Bricks" (696)](https://lu-explorer.web.app/missions/696)
- ["Made from Maelstrom" (1783)](https://lu-explorer.web.app/missions/1783)

My guess there is a database table entry that determines if an item is consumed knowing ["The Sentinel Shield" (939)](https://lu-explorer.web.app/missions/939) does not consume the item. Currently, not having this behavior results in undeletable inventory items getting stuck in the inventory and requiring a database modification to remove.

**Comment by Jettford** [comment]
Implemented Removal of items
