### ISSUE TITLE
Custom Chat Filters

### ISSUE THREAD

**Issue by TheNexusAvenger** [yuwui/Uchu#200]
The current chat system currently relies on a whitelist. While effective at blocking profanity, it makes conversations very limited at discussions to the point where conversations need to be facilities through third parties. I had a case in a test server where I was unable to get some information about an issue from someone because of the filter. Being able to disable the filter, and potentially being able to have custom filters (REST API? Blacklist option?) would be an improvement for some communities.

**Comment by Jettford** [comment]
Nope
