### ISSUE TITLE
Discovery Task (Achevement)

### ISSUE THREAD

**Issue by Samexahr** [yuwui/Uchu#223]
This is an achievement that occurs multiple times in most worlds that hasn't been fully implemented. It will need a trigger to activate the mission.

**Comment by Samexahr** [comment]
Summery of Dicord/Dev: Code Discover Task, - March 1st

used: https://lu-explorer.web.app/missions/706
Extra: https://github.com/Xiphoseer/lu-json
Primitives: https://github.com/UchuServer/Uchu/blob/dev/Uchu.World/Objects/Components/Server/PrimitiveModelComponent.cs

To test this code or make it work, logic will need to be implemented
 - Implement the Trigger in the Trigger Component (OnArrived?)
 - Implement LDF Key (POI) (POI value is the target Group, and has a 02_server script attached in LDF)
 - Trigger could be Area Tracking (unlikely) or a physics trigger (object?)
 - Primitive triggers may be helpful
Conclusion
 - Add a script with a listener
 - loop through the game objects to check POI key is correct
 - if so complete the mission of the player that entered the object/trigger

**Comment by Jettford** [comment]
Implemented
