### ISSUE TITLE
Objects Disappear

### ISSUE THREAD

**Issue by RunningPlasmaDog** [yuwui/Uchu#23]
Sometimes all objects disappear when completing missions.

**Comment by Wincent01** [comment]
Hello,

Which version of Uchu are you using at this time? Please note that the release version, the *.exe, lack a lot of bug fixes and features present in the current master branch.

Some more details on the bug would be appreciated. Could you post the last couple of log messages after you encounter the bug; any specific mission?

**Comment by RunningPlasmaDog** [comment]
I am using the Dev release 1. It happens on any mission. It's really just the NPCs that disappear. I am not aware how to access the log messages.

**Comment by Jettford** [comment]
The release doesn't log try and recreate the error and then copy and paste the console in a comment here.

**Comment by RunningPlasmaDog** [comment]
I assume that the bugs have been fixed since they would be readily apparent in the new master branch (that I am not aware how to install).

**Comment by RunningPlasmaDog** [comment]
The bug is fixed in the newest version.
