### ISSUE TITLE
Missions can't be accepted when progressing to a certain point

### ISSUE THREAD

**Issue by bombom737** [yuwui/Uchu#231]
The attached video shows examples of what I'm talking about. This started happening to me when I accepted Duke Exeter's mission titled "Forbidden Trophies" if I'm not mistaken.

https://user-images.githubusercontent.com/71724325/111027068-916d8780-83f6-11eb-95d0-487f83271202.mp4

**Comment by RedstoneParadox** [comment]
Uh, is the screen supposed to be turning to black randomly? Is that part of the issue?

**Comment by bombom737** [comment]
> Uh, is the screen supposed to be turning to black randomly? Is that part of the issue?

Oh crap, it's a rendering issue. Since the video, I deleted the minifig so I can't record another one right away. However, corrupted video or not, this issue is real.

**Comment by enteryournamehere** [comment]
This was likely fixed in #279, if the problem still persists feel free to re-open the issue.
