### ISSUE TITLE
Submodules aren't cloned when cloning Uchu

### ISSUE THREAD

**Issue by Jettford** [yuwui/Uchu#24]
I think it is just undo or redo whatever you did in the latest config

**Comment by Wincent01** [comment]
Hello,

How are you cloning Uchu?

If you’re cloning it via downloading the zip file, no sub modules will be included.

Try using the git cli with `--recurse-submodules`, this should ensure that all submodules are cloned alongside the repository.

**Comment by Jettford** [comment]
I was cloning via GitKraken and it hadn't included the RakDotNet or InfectedRose module but using the `--recurse-submodules` and a CLI git client worked but not sure why GitKraken is no longer cloning it my bad (It was just 2 people were having the same issue so I assumed it was a problem)
