### ISSUE TITLE
Mission "Gain Your Imagination" Bug

### ISSUE THREAD

**Issue by RunningPlasmaDog** [yuwui/Uchu#27]
Completing the mission "Gain Your Imagination" causes Bob and the player to both lock up and Bob does not give any more missions. I am using the most recent version of Uchu.

**Comment by Wincent01** [comment]
Hello,

Have you build the StandardScripts? If it's not build and specified in the config, that mission will not work.

Could you post the last couple of log message as well?

**Comment by RunningPlasmaDog** [comment]
I don't know exactly what log message to look for, but I am getting a message saying `[Warning]      No handler registered for GameMessage: NotifyServerLevelProcessingComplete!` There seems to be some errors mentioning the standard scripts, but I think I set them up correctly as all other missions seem to work. After I level up, Bob does not offer me the next mission.

**Comment by RunningPlasmaDog** [comment]
It seems that I have not built that. I assumed that the client would not let me in at all if it was working.
