### ISSUE TITLE
Damage taken after enemy is destroyed

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#28]
Health is lost even after smashing the enemy.

To replicate this: Smash an enemy, and stand where it died before it respawns. You will take damage in the same way it attacks.

**Comment by elenawinters** [comment]
This may have happened due to the client believing that the enemy is dead, while it isn't on the server.

Please verify that this is still happening and re-open the issue.

**Comment by MustacheMan2** [comment]
Issue still running strong. This also is relevant to #65, #53 and #61 as smashing any object after some point in the session will most often not register as smashing it in the first place. If the object is an enemy, they will attack you, including mechs throwing you in the air. At this point the bug will most likely persist until server restart where it will return shortly after. 
        You are more likely to get the object officially smashed by a jump-kick, while ground pounds rarely ever work at all. This might be related to the types of attacks since some weapons avoid this bug better than others, while consumables and abilities (e.g firecrackers, improved scythe of whirlwind ability) almost always register. I'd like to add that after the point of no return enemies can cease to attack at all (with or without AI enabled), although this is rarer. 
        The commit I am using is a couple months old but I doubt that affects this sort of bug at the moment, but if this is supposed to be fixed now I will update it.

**Comment by elenawinters** [comment]
I'm pretty sure this is related to the skill system.

Pinning this issue

**Comment by MickVermeulen** [comment]
Has to do with the client thinking an entity is smashed, while the server doesn't. As a result the AI is still calculated and the player is damaged. There's multiple causes for this and they're spread out over multiple other issues (e.g. damage miscalculation, not handling movement switch type 7 properly and invalid deserialization of sync handle).

**Comment by MustacheMan2** [comment]
I've found that this still occurs, just much less frequently. It happens the most when recording the game.
