### ISSUE TITLE
Spiderlings disappear

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#29]
When entering the spider cave in Avant Gardens, Spiderlings disappear when nearing them. Server restart respawns them, but cycle continues afterwards.

**Comment by Wincent01** [comment]
Uchu currently only supports pathfinding over terrain, so the meshes which make up the spider cave don’t get taken into account. 

This causes the spiders to be teleported to the bottom on the world where the terrain lies.

Disabling pathfinding will fix this issue.
