### ISSUE TITLE
Loading Venture Explorer Fails

### ISSUE THREAD

**Issue by NicoloLazzaroni** [yuwui/Uchu#305]
Hello,

I properly installed Uchu on a VPS providing it with a TLS certificate and a domain.
Everything is working fine until the character creation page. However, when trying to load Venture Explorer, the user gets stuck right before the video is played and the server last response is "`[Debug] [Char] Received Uchu.Char.JoinWorldRequest`".

After a few minutes the server aswers with:
```
[Info ] [Master] 73ddf51d-5d72-4fdf-8e61-1cd39d1faf07 is SeverelyLagging
[Info ] [Master] 73ddf51d-5d72-4fdf-8e61-1cd39d1faf07 is Unhealthy
[Info ] [Master] 73ddf51d-5d72-4fdf-8e61-1cd39d1faf07 is Dead
[Info ] [Master] Closing 73ddf51d-5d72-4fdf-8e61-1cd39d1faf07 (Dead) due to health status.
```

It once answered with:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Uchu.Master.Api.MasterCommands.AllocateWorld(String zone)
   at Uchu.Api.ApiManager.<>cDisplayClass21_0.<<StartAsync>b0>d.MoveNext()
```

Any idea to solve this issue?

Thank you for your time.

**Comment by enteryournamehere** [comment]
Make sure that in Uchu's config.xml `Hostname` (under `Networking`) is set to the domain of your VPS. The server sends this value to the client, which then uses it as the address for world servers.

**Comment by NicoloLazzaroni** [comment]
Hostname is right, it is a subdomain connected to the VPS IP.

**Comment by NicoloLazzaroni** [comment]
After reinstalling the VPS it seems like it is working, maybe a port or firewall issue.
I would mark it as solved, thank you for your help.
