### ISSUE TITLE
birds can't be scared away

### ISSUE THREAD

**Issue by MickVermeulen** [yuwui/Uchu#46]
the birds during the AG statue run can't be scared away, requiring /complete

**Comment by MustacheMan2** [comment]
This requires a script I believe so it wouldn't be considered a bug...

**Comment by MickVermeulen** [comment]
Agree, changed to enhancement.

**Comment by Jettford** [comment]
Yeah I think this was missed as it required physics collisions, it should be a pretty easy script to implement.

**Comment by Jettford** [comment]
This script was implemented in a idle branch, it has now been implemented in master
