### ISSUE TITLE
the new message screen can't be closed

### ISSUE THREAD

**Issue by MickVermeulen** [yuwui/Uchu#48]
When opening a mailbox, messages can be composed and received but the screen can't be closed, as a result the client has to relog to gain access over their character again.

**Comment by Jettford** [comment]
This isn't a bug this is just something that isn't implemented

In the clients mail handler script it has a function called onTerminateInteraction which is called when the player tries to close the mail UI
```lua
function onTerminateInteraction(self,msg)
    local player = GAMEOBJ:GetObjectByID(GAMEOBJ:GetLocalCharID())
    
    -- Turn OFF Mail UI
    self:FireEventServerSide{args = "toggleMail", senderID = player} 
end
```
As you can see in the script it triggers a server side event with the args "toggleMail" so theoretically all we need to do is add a listener that will trigger the mail UI 

```cs
player.OnFireServerEvent.AddListener("toggleMail", async message => { Uchu.World.Social.UIHelper.ToggleAsync(player, "ToggleMail", false); });
```
There may be more to this but as far as I am aware it is that simple
