### ISSUE TITLE
Mech throws player upwards after getting smashed

### ISSUE THREAD

**Issue by VaiskiKP** [yuwui/Uchu#61]
Mech throws player upwards after getting smashed. Also while I was in the air I couldn't start a double jump, so it probably was another state than jumping. It kinda felt and looks more like I was falling upwards for a moment. 
[Video](https://youtu.be/QACi7nvrT-w)

**Comment by elenawinters** [comment]
This appears to be similar and/or related to 2 other issues:
https://github.com/yuwui/Uchu/issues/22
https://github.com/yuwui/Uchu/issues/28

As such, I'm going to mark this as a duplicate, although any further information I want to be posted to this issue.

**Comment by Jettford** [comment]
I am not sure this is a AI issue, which the other ones are

**Comment by elenawinters** [comment]
I believe this is a skill system issue. I'm not certain on that though.
