### ISSUE TITLE
remove physics logging

### ISSUE THREAD

**Issue by MickVermeulen** [yuwui/Uchu#64]
currently all physics are logged creating tons of messages like:

[1004088507069542417] "MegaSpaceVortex" stayed [70368747895174] "PrimitiveModel phantom (humans only)"

this floods the logs and isn't necessary.

**Comment by Jettford** [comment]
Yeah logging might need to be refactored entirely because things like every time a object loads don't need to be logged, it is difficult to get actual information from

**Comment by MickVermeulen** [comment]
I'm also a fan of hiding the world info packets specifically

**Comment by elenawinters** [comment]
I'm against removing it.

It's a debug message right? Debugging is kinda supposed to show everything that's going on in my opinion.

**Comment by MickVermeulen** [comment]
True, but currently it's not at debug level but at information level so even that change would be nice.

**Comment by Jettford** [comment]
I have moved this log to debug in the latest PR, is this suffice?
