### ISSUE TITLE
Mobs Ain't Dropping Loot

### ISSUE THREAD

**Issue by Harcronium** [yuwui/Uchu#65]
After while, 90% of the mobs I kill won't drop their loot.  I am not sure if it is lag or an issue with the code.

**Comment by Harcronium** [comment]
P.S This glitch does stop eventually.  It persisted for about 5 to 10 minutes.

**Comment by MickVermeulen** [comment]
Labeled as "AI" because this is probably caused by performance issues from the tick/AI handling of combat.

**Comment by elenawinters** [comment]
Same likely cause as https://github.com/yuwui/Uchu/issues/61 and https://github.com/yuwui/Uchu/issues/28

**Comment by Harcronium** [comment]
Thanks!
